variables:
  INTELLIJ_LATEST_VERSION: 2018.2.2
  INTELLIJ_IMAGE_LATEST: registry.gitlab.com/$CI_PROJECT_PATH/intellij/$INTELLIJ_LATEST_VERSION
  INTELLIJ_IMAGE_LATEST_JOB_TAG: registry.gitlab.com/$CI_PROJECT_PATH/intellij/$INTELLIJ_LATEST_VERSION:$CI_BUILD_REF

  INTELLIJ_LATEST_MINUS_ONE_VERSION: 2018.1.6
  INTELLIJ_IMAGE_LATEST_MINUS_ONE: registry.gitlab.com/$CI_PROJECT_PATH/intellij/$INTELLIJ_LATEST_MINUS_ONE_VERSION
  INTELLIJ_IMAGE_LATEST_MINUS_ONE_JOB_TAG: registry.gitlab.com/$CI_PROJECT_PATH/intellij/$INTELLIJ_LATEST_MINUS_ONE_VERSION:$CI_BUILD_REF

stages:
- build
- verify
- verify-aggregate
- deploy
- publish
- verify-publish

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .gradle/

build:
  image: openjdk:8
  stage: build
  retry: 2
  script:
  - chmod +x gradlew
  - ./gradlew assembleRelease
  artifacts:
    paths:
    - ./build/release
    - ./.m2

build:image:
  image: docker:git
  stage: build
  retry: 2
  services:
  - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
  - cd ./image/intellij-ce
  - docker pull $INTELLIJ_IMAGE_LATEST || true
  - docker build --cache-from $INTELLIJ_IMAGE_LATEST --tag $INTELLIJ_IMAGE_LATEST_JOB_TAG --tag $INTELLIJ_IMAGE_LATEST --build-arg INTELLIJ_VERSION=$INTELLIJ_LATEST_VERSION .
  - docker push $INTELLIJ_IMAGE_LATEST
  - docker pull $INTELLIJ_IMAGE_LATEST_MINUS_ONE || true
  - docker build --cache-from $INTELLIJ_IMAGE_LATEST_MINUS_ONE --tag $INTELLIJ_IMAGE_LATEST_MINUS_ONE_JOB_TAG --tag $INTELLIJ_IMAGE_LATEST_MINUS_ONE --build-arg INTELLIJ_VERSION=$INTELLIJ_LATEST_MINUS_ONE_VERSION .
  - docker push $INTELLIJ_IMAGE_LATEST_MINUS_ONE

unit-test:
  image: openjdk:8
  stage: verify
  retry: 2
  script:
  - chmod +x gradlew
  - ./gradlew test
  artifacts:
    paths:
    - ./build
    - ./intellij2checkstyle-core/build
    - ./intellij2checkstyle-cmd/build
    - ./intellij2checkstyle-gradle/build
    when: always

integration-test:intellij-ce-latest:
  image: $INTELLIJ_IMAGE_LATEST_JOB_TAG
  stage: verify
  retry: 2
  script:
  - chmod +x gradlew
  - ./gradlew :intellij2checkstyle-core:integrationTest
  artifacts:
    paths:
    - ./build
    - ./intellij2checkstyle-core/build
    - ./intellij2checkstyle-cmd/build
    - ./intellij2checkstyle-gradle/build
    when: always

integration-test:intellij-ce-latest-minus-one:
  image: $INTELLIJ_IMAGE_LATEST_MINUS_ONE_JOB_TAG
  stage: verify
  retry: 2
  script:
  - chmod +x gradlew
  - ./gradlew :intellij2checkstyle-core:integrationTest
  artifacts:
    paths:
    - ./build
    - ./intellij2checkstyle-core/build
    - ./intellij2checkstyle-cmd/build
    - ./intellij2checkstyle-gradle/build
    when: always

full-test:gradle-plugin:
  image: $INTELLIJ_IMAGE_LATEST_JOB_TAG
  stage: verify
  retry: 2
  script:
  - chmod +x gradlew
  - ./gradlew :intellij2checkstyle-core:gradleIntegrationTest
  dependencies:
  - build
  artifacts:
    paths:
    - ./build/
    - ./intellij2checkstyle-core/build
    - ./intellij2checkstyle-cmd/build
    - ./intellij2checkstyle-gradle/build
    when: always

full-test:command-line-client:
  image: $INTELLIJ_IMAGE_LATEST_JOB_TAG
  stage: verify
  retry: 2
  script:
  - chmod +x gradlew
  - ./gradlew :intellij2checkstyle-core:cmdIntegrationTest
  dependencies:
  - build
  artifacts:
    paths:
    - ./build
    - ./intellij2checkstyle-core/build
    - ./intellij2checkstyle-cmd/build
    - ./intellij2checkstyle-gradle/build
    when: always

lint:
  image: openjdk:8
  stage: verify
  retry: 2
  script:
  - chmod +x gradlew
  - ./gradlew violations

verify-aggregate:
  image: openjdk:8
  stage: verify-aggregate
  retry: 2
  dependencies:
  - unit-test
  - integration-test:intellij-ce-latest
  - integration-test:intellij-ce-latest-minus-one
  - full-test:gradle-plugin
  - full-test:command-line-client
  script:
  - chmod +x gradlew
  - ./gradlew jacocoRootReport
  - cat ./build/reports/jacoco/jacocoRootReport/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
    - ./build
    - ./intellij2checkstyle-core/build
    - ./intellij2checkstyle-cmd/build
    - ./intellij2checkstyle-gradle/build
    when: always

pages:
  image: openjdk:8
  stage: deploy
  retry: 2
  cache: {}
  dependencies:
  - verify-aggregate
  script:
  - mkdir --parents public/coverage/
  - mkdir --parents public/tests/
  - mv ./build/reports/jacoco/jacocoRootReport/html/* public/coverage/
  artifacts:
    paths:
    - public
  only:
  - master

publish:
  image: openjdk:8
  stage: publish
  retry: 2
  script:
  - chmod +x gradlew
  - ./gradlew assembleRelease
  - ./gradlew :intellij2checkstyle-core:bintrayUpload -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY
  - ./gradlew :intellij2checkstyle-gradle:publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
  when: manual
  only:
  - master

verify-publish:
  image: $INTELLIJ_IMAGE_LATEST_JOB_TAG
  stage: verify-publish
  retry: 2
  dependencies:
  - publish
  script:
  - chmod +x gradlew
  - ./gradlew assembleRelease
  - ./gradlew :intellij2checkstyle-core:gradleGlobalTest
  when: manual
  only:
  - master

