package de.theodm.intellij2checkstyle.convert

import de.theodm.intellij2checkstyle.Intellij2Checkstyle
import de.theodm.intellij2checkstyle.convert.reporters.checkstyle.CheckstyleReporter
import de.theodm.intellij2checkstyle.convert.reporters.plaintext.PlaintextReporter
import picocli.CommandLine
import java.nio.file.Paths

@CommandLine.Command(
    name = "convert"
)
@Suppress("LateinitUsage")
internal class ConvertCommand : Runnable {
    @field:CommandLine.Option(
        names = ["-co", "--checkstyle-output-file"],
        defaultValue = "intellij2checkstyle.xml"
    )
    private lateinit var checkstyleOutputFile: String

    @field:CommandLine.Option(
        names = ["-po", "--plaintext-output-file"],
        defaultValue = "intellij2checkstyle.txt"
    )
    private lateinit var plaintextOutputFile: String

    @field:CommandLine.Parameters(
        index = "0",
        description = ["Path to the report set folder, " +
            "which was generated by an intellij inspections run."]
    )
    private lateinit var reportSetFolder: String

    @field:CommandLine.Parameters(
        index = "1",
        description = ["Path to the root of the analyzed project."]
    )
    private lateinit var projectFolderPath: String

    override fun run() {
        Intellij2Checkstyle.convert(
            reportSetFolderPath = Paths.get(this.reportSetFolder),
            projectFolderPath = Paths.get(this.projectFolderPath),
            reporter = listOf(
                CheckstyleReporter(Paths.get(checkstyleOutputFile)),
                PlaintextReporter(Paths.get(plaintextOutputFile))
            )
        )
    }
}
