package de.theodm.intellij2checkstyle.convert

import de.theodm.intellij2checkstyle.Intellij2Checkstyle
import picocli.CommandLine
import java.nio.file.Paths

@CommandLine.Command(
    name = "convert"
)
@Suppress("LateinitUsage")
internal class ConvertCommand : Runnable {
    @field:CommandLine.Option(
        names = ["-o", "--output-file"],
        defaultValue = "intellij2checkstyle.xml"
    )
    private lateinit var outputFile: String

    @field:CommandLine.Parameters(
        index = "0",
        description = ["Path to the report set folder, " +
            "which was generated by an intellij inspections run."]
    )
    private lateinit var reportSetFolder: String

    @field:CommandLine.Parameters(
        index = "1",
        description = ["Path to the root of the analyzed project."]
    )
    private lateinit var projectFolderPath: String

    override fun run() {
        Intellij2Checkstyle.convert(
            Paths.get(this.reportSetFolder),
            Paths.get(this.projectFolderPath),
            Paths.get(this.outputFile)
        )
    }
}
